name: Deploy UI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install the Angular CLI
        run: npm install -g @angular/cli

      - name: Install Angular CLI GitHub Pages
        run: npm install -g angular-cli-ghpages

      - name: Install Dependencies
        run: npm install
        working-directory: ImageEventUI

      - name: Build
        run: ng build --configuration production --base-href "https://the-running-dev.github.io/Demo-ImageEventProcessor/"
        working-directory: ImageEventUI

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/image-event-ui/browser --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ImageEventUI